name: Azure Terraform Import

on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  import:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false 

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan and Generate Config
        
        run: terraform plan -generate-config-out=generated_code.tf

      - name: Terraform Show
       
        run: terraform show -no-color > imported_state.txt

      - name: Upload Import Results
        
        uses: actions/upload-artifact@v4
        with:
          name: terraform-import-results
          path: |
            generated_code.tf
            imported_state.txt
